export const symptomsWomen = [
  'Dolor articular',
  'Dolor de cabeza',
  'Fatiga por la mañana',
  'Fatiga por la tarde',
  'Estrés',
  'Perturbación del sueño',
  'Sudores nocturnos',
  'Cambios de humor frecuentes',
  'Irritabilidad',
  'Nerviosismo',
  'Depresión',
  'Ansiedad',
  'Ganas frecuentes de llorar',
  'Lapsos de pérdida de memoria',
  'Pensamiento confuso',
  'Bocio (problemas de tiroides)',
  'Incontinencia',
  'Aumento en la urgencia de orinar',
  'Temperatura corporal fría',
  'Inflamación de cara/bolsas en ojos',
  'Disminución de sudoración',
  'Adelgazamiento de la piel',
  'Pérdida auditiva',
  'Voz ronca/cambios de voz',
  'Incremento de vello corporal/facial',
  'Bajo nivel de glucosa en sangre',
  'Sensibilidad a químicos',
  'Alergias',
  'Pérdida de cabello',
  'Cabello débil, seco, quebradizo',
  'Envejecimiento prematuro',
  'Infertilidad',
  'Antojo de azúcar',
  'Estreñimiento',
  'Acné',
  'Disminución de la masa muscular',
  'Pérdida de densidad ósea',
  'Fibromialgia',
  'Cáncer de mama',
  'Cambios de flujo de sangrado',
  'Resequedad vaginal',
  'Senos sensibles',
  'Senos fibroquísticos',
  'Aumento de peso en caderas',
  'Aumento de peso en cintura',
  'Disminución del libido',
  'Pérdida de vigor/resistencia sexual',
  'Fibromas uterinos',
  'Alta presión arterial',
  'Baja presión arterial',
  'Frecuencia cardiaca baja',
  'Colesterol elevado',
  'Palpitaciones cardiacas',
  'Triglicéridos elevados',
  'Ritmo cardiaco rápido',
  'Adormecimiento de pies/manos',
]
export const symptomsMen = [
  'Dolor articular',
  'Dolor muscular',
  'Dolor de cabeza',
  'Dolor de cuello/espalda',
  'Fatiga por la mañana',
  'Fatiga por la tarde',
  'Estrés',
  'Dificultad para dormir',
  'Sudores nocturnos',
  'Irritabilidad',
  'Comportamiento agresivo',
  'Nerviosismo',
  'Apatía',
  'Depresión',
  'Ansiedad',
  'Fatiga mental',
  'Lapsos de pérdida de memoria',
  'Disminución de la agudeza mental',
  'Bocio (problemas de tiroides)',
  'Aumento en la urgencia de orinar',
  'Disminución en la urgencia de orinar',
  'Disminución del flujo urinario',
  'Temperatura corporal fría',
  'Inflamación de cara/bolsas en ojos',
  'Disminución de sudoración',
  'Adelgazamiento de la piel',
  'Pérdida auditiva',
  'Voz ronca/cambios de voz',
  'Bajo nivel de glucosa en sangre',
  'Sensibilidad a químicos',
  'Alergias',
  'Cabello débil, seco, quebradizo',
  'Piel o cabello grasos',
  'Uñas débiles/quebradizas',
  'Bochornos',
  'Pérdida de flexibilidad',
  'Envejecimiento prematuro',
  'Infertilidad',
  'Antojo de azúcar',
  'Zumbidos en los oídos',
  'Mareos',
  'Estreñimiento',
  'Acné',
  'Disminución de la masa muscular',
  'Pérdida de densidad ósea',
  'Disminución de erecciones',
  'Problemas de próstata',
  'Cáncer de próstata',
  'Aumento de peso en pecho y caderas',
  'Aumento de peso en cintura',
  'Disminución del libido',
  'Pérdida de vigor/resistencia sexual',
  'Alta presión arterial',
  'Baja presión arterial',
  'Baja frecuencia cardíaca',
  'Colesterol elevado',
  'Palpitaciones cardiacas',
  'Triglicéridos elevados',
  'Ritmo cardiaco rápido',
  'Adormecimiento de pies/manos',
]

export const tips = {
  'Problemas de próstata': 'Por ejemplo: hiperplasia prostática benigna',
  'Disminución del libido': 'Deseo sexual',
  'Perturbación del sueño': 'Problemas para dormir, problemas para despertar, insomnio',
  'Senos fibroquísticos': 'Engrosamiento del tejido mamario o quistes en una o ambas mamas',
  'Fibromas uterinos': 'Tumores benignos del útero',
}
