export const symptomsAll = [
  'Dolor articular',
  'Dolor muscular',
  'Dolor de cabeza',
  'Dolor de cuello/espalda',
  'Fatiga por la mañana',
  'Fatiga por la tarde',
  'Estrés',
  'Perturbación del sueño',
  'Dificultad para dormir',
  'Sudores nocturnos',
  'Cambios de humor frecuentes',
  'Irritabilidad',
  'Nerviosismo',
  'Apatía',
  'Depresión',
  'Ansiedad',
  'Ganas frecuentes de llorar',
  'Fatiga mental',
  'Lapsos de pérdida de memoria',
  'Pensamiento confuso',
  'Disminución de la agudeza mental',
  'Pérdida de cabello',
  'Cabello débil, seco, quebradizo',
  'Uñas débiles/quebradizas',
  'Retención de líquidos',
  'Bochornos',
  'Pérdida de flexibilidad',
  'Envejecimiento prematuro',
  'Infertilidad',
  'Infecciones recurrentes',
  'Cicatrización lenta',
  'Estreñimiento',
  'Acné',
  'Disminución de la masa muscular',
  'Pérdida de densidad ósea',
  'Fibromialgia',
]

export const symptomsWomen = [
  'Cambios de flujo de sangrado',
  'Resequedad vaginal',
  'Senos sensibles',
  'Senos fibroquísticos',
]

export const tips = {
  'Perturbación del sueño': 'Problemas para dormir, problemas para despertar, insomnio',
  Fibromialgia: 'Dolor corporal generalizado',
}
